language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: nightly
    - php: hhvm

sudo: false

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction

script:
  - mkdir -p build/logs
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - if [ "$TRAVIS_PHP_VERSION" != "nightly" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" != "nightly" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
